python main_clip.py --config configs_clip.json --random-seed 10 --max-gens 2500 --save-folder red_square
python main_clip.py --config configs_clip.json --random-seed 11 --max-gens 2500 --save-folder red_square
python main_clip.py --config configs_clip.json --random-seed 12 --max-gens 2500 --save-folder red_square
python main_clip.py --config configs_clip.json --random-seed 13 --max-gens 2500 --save-folder red_square
python main_clip.py --config configs_clip.json --random-seed 14 --max-gens 2500 --save-folder red_square
python main_clip.py --config configs_clip.json --random-seed 15 --max-gens 2500 --save-folder red_square
python main_clip.py --config configs_clip.json --random-seed 16 --max-gens 2500 --save-folder red_square
python main_clip.py --config configs_clip.json --random-seed 17 --max-gens 2500 --save-folder red_square
python main_clip.py --config configs_clip.json --random-seed 18 --max-gens 2500 --save-folder red_square
python main_clip.py --config configs_clip.json --random-seed 19 --max-gens 2500 --save-folder red_square
python main_clip.py --config configs_clip.json --random-seed 20 --max-gens 2500 --save-folder red_square
python main_clip.py --config configs_clip.json --random-seed 21 --max-gens 2500 --save-folder red_square
python main_clip.py --config configs_clip.json --random-seed 22 --max-gens 2500 --save-folder red_square
python main_clip.py --config configs_clip.json --random-seed 23 --max-gens 2500 --save-folder red_square
python main_clip.py --config configs_clip.json --random-seed 24 --max-gens 2500 --save-folder red_square
python main_clip.py --config configs_clip.json --random-seed 25 --max-gens 2500 --save-folder red_square
python main_clip.py --config configs_clip.json --random-seed 26 --max-gens 2500 --save-folder red_square
python main_clip.py --config configs_clip.json --random-seed 27 --max-gens 2500 --save-folder red_square
python main_clip.py --config configs_clip.json --random-seed 28 --max-gens 2500 --save-folder red_square
python main_clip.py --config configs_clip.json --random-seed 29 --max-gens 2500 --save-folder red_square
python main_clip.py --config configs_clip.json --random-seed 30 --max-gens 2500 --save-folder red_square